name: GitHub Metrics

on:
  schedule:
    # 12AM EST (midnight)
    - cron: '0 5 * * *'
  workflow_dispatch:
  # run on push to this repository's main branch
  push: {branches: ["main"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    if: "github.repository == 'servusdei2018/servusdei2018'"
    steps:
      - name: 🙋 Introduction plugin
        uses: lowlighter/metrics@latest
        if: ${{ success() || failure() }}
        with:
          filename: metrics.classic.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: header, activity, community, repositories, metadata
          plugin_notable: yes
          plugin_notable_from: organization  # Display notable contributions to organizations only
          plugin_notable_filter: stars:>500  # Count contributions as notable if stars > 500
          plugin_notable_repositories: yes   # Display org/repo

      - name: 🏆 Achievements
        uses: lowlighter/metrics@latest
        if: ${{ success() || failure() }}
        with:
          filename: metrics.plugin.achievements.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_achievements: yes
          plugin_achievements_threshold: B       # Display achievements with rank B or higher
          plugin_achievements_secrets: yes       # Display unlocked secrets achievements
          plugin_achievements_ignored: octonaut  # Hide octonaut achievement
          plugin_achievements_limit: 0           # Display all unlocked achievement matching threshold and secrets params
      
      - name: 🎭 Reactions plugin
        uses: lowlighter/metrics@latest
        if: ${{ success() || failure() }}
        with:
          filename: metrics.plugin.reactions.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_reactions: yes
          plugin_reactions_limit: 200                 # Compute reactions over last 200 issue comments
          plugin_reactions_limit_issues: 100          # Compute reactions over last 100 issues/pull requests opened
          plugin_reactions_days: 14                   # Compute reactions on issue comments posted less than 14 days ago
          plugin_reactions_details: count, percentage # Display reactions count and percentage
          plugin_reactions_ignored: bot               # Ignore "bot" user

      - name: 🈷️ Languages plugin
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@master
        with:
          filename: metrics.plugin.languages.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_languages: yes
          plugin_languages_ignored: html, css, tex, less, dockerfile, makefile, qmake, lex, cmake, shell
          plugin_languages_limit: 8
